name: Daily Twitter to Discord

on:
  schedule:
    - cron: '0 10 * * *'  # Ogni giorno alle 10:00 UTC
  workflow_dispatch:      # permette di far partire il workflow manualmente

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests

      - name: Run bot
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py
